import BaseApplicationGenerator from 'generator-jhipster/generators/base-application';

import { fixBlueprintPackagePath } from '../generator-rust-constants.js';

export default class extends BaseApplicationGenerator {
  constructor(args, opts, features) {
    super(args, opts, {
      ...features,
      queueCommandTasks: true,
      sbsBlueprint: true,
    });
    fixBlueprintPackagePath(this);
  }

  get [BaseApplicationGenerator.COMPOSING]() {
    return this.asComposingTaskGroup({
      async composingTemplateTask() {},
    });
  }

  get [BaseApplicationGenerator.POST_WRITING]() {
    return this.asPostWritingTaskGroup({
      async addPopperDependency({ application }) {
        // @popperjs/core is a peer dependency of @ng-bootstrap/ng-bootstrap and bootstrap.
        // It must be explicitly listed so that npm install --legacy-peer-deps (used in
        // the Dockerfile) resolves it correctly.
        if (application.clientFrameworkAngular) {
          const clientPackageJson = this.createStorage(this.destinationPath(application.clientRootDir, 'package.json'));
          clientPackageJson.merge({
            dependencies: {
              '@popperjs/core': '2.11.8',
            },
          });
        }
      },
      async fixSwaggerUiDevAssets({ application }) {
        // The Vite-based Angular dev server (used by `ng serve` since Angular 17+)
        // does not honor `assets` glob entries that pull files in from `node_modules/`,
        // so JHipster's Swagger UI bundles (`swagger-ui-bundle.js`, `swagger-ui.css`,
        // `axios.min.js`) silently 404 in dev mode and the iframe at /admin/docs is
        // blank. The production build still copies them correctly. Vendor the runtime
        // assets into `client/src/swagger-ui/` via a `prestart`/`postinstall` script
        // so the dev server treats them as plain static files.
        if (application.skipClient || !application.clientFrameworkAngular || !application.clientRootDir) return;

        const clientPackageJson = this.createStorage(this.destinationPath(application.clientRootDir, 'package.json'));
        const currentScripts = clientPackageJson.get('scripts') || {};
        const copyCmd = 'node scripts/copy-swagger-ui-assets.cjs';

        // Compose with any existing prestart/postinstall hooks instead of clobbering them.
        const compose = (existing, cmd) => {
          if (!existing) return cmd;
          if (existing.includes(cmd)) return existing;
          return `${existing} && ${cmd}`;
        };
        clientPackageJson.merge({
          scripts: {
            prestart: compose(currentScripts.prestart, copyCmd),
            postinstall: compose(currentScripts.postinstall, copyCmd),
          },
        });

        // Write the helper script that resolves the swagger-ui-dist + axios files via
        // `require.resolve` (so it works whether npm hoists them to the root workspace
        // node_modules or installs them under client/node_modules) and copies them into
        // `src/swagger-ui/` next to the JHipster-shipped index.html.
        const scriptBody = `// Auto-generated by generator-jhipster-rust.
// Copies the swagger-ui runtime assets next to client/src/swagger-ui/index.html so
// that the Vite-based Angular dev server can serve them in dev mode (it does not
// honor angular.json glob assets sourced from node_modules at runtime).
const fs = require('node:fs');
const path = require('node:path');

// Resolve a package's installation directory regardless of whether the package
// uses the modern \`exports\` field (which can block direct subpath resolves).
function resolvePackageDir(pkgName) {
  try {
    return path.dirname(require.resolve(pkgName + '/package.json'));
  } catch {
    return null;
  }
}

const dest = path.join(__dirname, '..', 'src', 'swagger-ui');
const swaggerUiDir = resolvePackageDir('swagger-ui-dist');
const axiosDir = resolvePackageDir('axios');

const filesToCopy = [];
if (swaggerUiDir) {
  filesToCopy.push(
    [path.join(swaggerUiDir, 'swagger-ui-bundle.js'), 'swagger-ui-bundle.js'],
    [path.join(swaggerUiDir, 'swagger-ui-standalone-preset.js'), 'swagger-ui-standalone-preset.js'],
    [path.join(swaggerUiDir, 'swagger-ui.css'), 'swagger-ui.css'],
    [path.join(swaggerUiDir, 'favicon-16x16.png'), 'favicon-16x16.png'],
    [path.join(swaggerUiDir, 'favicon-32x32.png'), 'favicon-32x32.png'],
  );
}
if (axiosDir) {
  filesToCopy.push([path.join(axiosDir, 'dist', 'axios.min.js'), 'axios.min.js']);
}

fs.mkdirSync(dest, { recursive: true });
let copied = 0;
for (const [src, name] of filesToCopy) {
  try {
    fs.copyFileSync(src, path.join(dest, name));
    copied += 1;
  } catch (err) {
    console.warn(\`[swagger-ui-assets] Could not copy \${src}: \${err.message}\`);
  }
}
console.log(\`[swagger-ui-assets] Copied \${copied}/\${filesToCopy.length} files into \${dest}\`);
`;
        this.writeDestination(this.destinationPath(application.clientRootDir, 'scripts/copy-swagger-ui-assets.cjs'), scriptBody);

        // Keep the auto-copied dist assets out of git noise. The JHipster-shipped
        // index.html in the same directory is left intentionally tracked.
        const gitignoreBody = `# Auto-copied by scripts/copy-swagger-ui-assets.cjs (do not commit)
swagger-ui-bundle.js
swagger-ui-standalone-preset.js
swagger-ui.css
favicon-16x16.png
favicon-32x32.png
axios.min.js
`;
        this.writeDestination(this.destinationPath(application.clientRootDir, 'src/swagger-ui/.gitignore'), gitignoreBody);
      },
      async addRootClientWorkspaceScripts({ application }) {
        // Forward common client lifecycle scripts (start, build, test, lint) from the
        // workspace root to the client/ workspace package. JHipster's base layout
        // assumes the client lives at the root, so when our blueprint moves it into a
        // workspace subfolder these scripts disappear from `npm run` at the project
        // root and users have to `cd client && npm start`. Restore them as workspace
        // forwarders so the user experience matches base JHipster.
        if (application.skipClient || !application.clientRootDir) return;

        const rootPackageJson = this.createStorage(this.destinationPath('package.json'));
        const clientWorkspace = application.clientRootDir.replace(/\/$/, '');
        const forwardedScripts = {
          start: `npm run -w ${clientWorkspace}/ start`,
          build: `npm run -w ${clientWorkspace}/ build`,
          test: `npm run -w ${clientWorkspace}/ test`,
          lint: `npm run -w ${clientWorkspace}/ lint`,
        };
        // Only add scripts that don't already exist in the root, to avoid clobbering
        // any backend scripts the base generator may have written.
        const currentScripts = rootPackageJson.get('scripts') || {};
        const additions = {};
        for (const [name, command] of Object.entries(forwardedScripts)) {
          if (currentScripts[name] === undefined) {
            additions[name] = command;
          }
        }
        if (Object.keys(additions).length > 0) {
          rootPackageJson.merge({ scripts: additions });
        }
      },
    });
  }

  get [BaseApplicationGenerator.POST_WRITING_ENTITIES]() {
    return this.asPostWritingEntitiesTaskGroup({
      async fixWorkspaceOverrides({ application }) {
        // npm overrides use `$react`/`$react-dom` to reference the version from
        // the SAME package.json's dependencies. In a workspace layout the root
        // package.json has the overrides but `react` lives in client/package.json,
        // so the `$` self-reference cannot resolve and `npm install` from the
        // root prints a long wall of `ERESOLVE overriding peer dependency`
        // warnings. Rewrite the root override entries with the explicit version
        // strings read from the client workspace package.json.
        //
        // Runs in POST_WRITING_ENTITIES (NOT POST_WRITING) because the base
        // React generator's `clientBundler` task writes `$react` into the root
        // package.json during POST_WRITING; we need to run after every
        // POST_WRITING task across all composed generators but BEFORE mem-fs
        // commits to disk so we don't trigger an overwrite-conflict prompt.
        if (!application.clientFrameworkReact || application.skipClient || !application.clientRootDir) return;

        const clientPackageJson = this.createStorage(this.destinationPath(application.clientRootDir, 'package.json'));
        const dependencies = clientPackageJson.get('dependencies') || {};
        const reactVersion = dependencies.react;
        const reactDomVersion = dependencies['react-dom'];
        if (!reactVersion) return;

        const rootPackageJson = this.createStorage(this.destinationPath('package.json'));
        const overrides = rootPackageJson.get('overrides') || {};
        if (!overrides['react-redux-loading-bar']) return;

        rootPackageJson.merge({
          overrides: {
            'react-redux-loading-bar': {
              react: reactVersion,
              'react-dom': reactDomVersion || reactVersion,
            },
          },
        });
      },
    });
  }
}
